# Generated by Django 3.2.18 on 2023-04-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoutouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
