# Generated by Django 3.2.18 on 2023-04-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoutouts', '0002_alter_milestone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='highlighted',
        ),
    ]
