# Generated by Django 3.2.18 on 2023-04-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('stacktime', models.DateTimeField()),
                ('stackleader', models.CharField(max_length=100)),
            ],
        ),
    ]
