# Generated by Django 3.2.18 on 2023-04-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelofondo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='length',
        ),
    ]
