# Generated by Django 3.2.18 on 2023-04-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelofondo', '0003_ride_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='stackleader',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='stacktime',
            field=models.DateTimeField(null=True),
        ),
    ]
